name: yaml_mapper
description: A simple YAML Map parser.
version: 0.0.1
homepage: https://github.com/Arwed-M/yaml_mapper

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: